(cl:defpackage pkg-srv
  (:use )
  (:export
   "SERVS"
   "<SERVS-REQUEST>"
   "SERVS-REQUEST"
   "<SERVS-RESPONSE>"
   "SERVS-RESPONSE"
   "WORDCOUNT"
   "<WORDCOUNT-REQUEST>"
   "WORDCOUNT-REQUEST"
   "<WORDCOUNT-RESPONSE>"
   "WORDCOUNT-RESPONSE"
  ))

