// Generated by gencpp from file pkg/complexMsg.msg
// DO NOT EDIT!


#ifndef PKG_MESSAGE_COMPLEXMSG_H
#define PKG_MESSAGE_COMPLEXMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg
{
template <class ContainerAllocator>
struct complexMsg_
{
  typedef complexMsg_<ContainerAllocator> Type;

  complexMsg_()
    : first(0)
    , second(0)
    , output()  {
    }
  complexMsg_(const ContainerAllocator& _alloc)
    : first(0)
    , second(0)
    , output(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _first_type;
  _first_type first;

   typedef uint32_t _second_type;
  _second_type second;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::pkg::complexMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg::complexMsg_<ContainerAllocator> const> ConstPtr;

}; // struct complexMsg_

typedef ::pkg::complexMsg_<std::allocator<void> > complexMsg;

typedef boost::shared_ptr< ::pkg::complexMsg > complexMsgPtr;
typedef boost::shared_ptr< ::pkg::complexMsg const> complexMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg::complexMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg::complexMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg::complexMsg_<ContainerAllocator1> & lhs, const ::pkg::complexMsg_<ContainerAllocator2> & rhs)
{
  return lhs.first == rhs.first &&
    lhs.second == rhs.second &&
    lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg::complexMsg_<ContainerAllocator1> & lhs, const ::pkg::complexMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg::complexMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg::complexMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg::complexMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg::complexMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg::complexMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg::complexMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg::complexMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f32a42f2c7e66e689db49e99986c6e91";
  }

  static const char* value(const ::pkg::complexMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf32a42f2c7e66e68ULL;
  static const uint64_t static_value2 = 0x9db49e99986c6e91ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg::complexMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg/complexMsg";
  }

  static const char* value(const ::pkg::complexMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg::complexMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 first\n"
"uint32 second\n"
"string output\n"
;
  }

  static const char* value(const ::pkg::complexMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg::complexMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct complexMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg::complexMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg::complexMsg_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.second);
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_MESSAGE_COMPLEXMSG_H
