// Generated by gencpp from file pkg/servs.msg
// DO NOT EDIT!


#ifndef PKG_MESSAGE_SERVS_H
#define PKG_MESSAGE_SERVS_H

#include <ros/service_traits.h>


#include <pkg/servsRequest.h>
#include <pkg/servsResponse.h>


namespace pkg
{

struct servs
{

typedef servsRequest Request;
typedef servsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct servs
} // namespace pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg::servs > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pkg::servs&) { return value(); }
};

template<>
struct DataType< ::pkg::servs > {
  static const char* value()
  {
    return "pkg/servs";
  }

  static const char* value(const ::pkg::servs&) { return value(); }
};


// service_traits::MD5Sum< ::pkg::servsRequest> should match
// service_traits::MD5Sum< ::pkg::servs >
template<>
struct MD5Sum< ::pkg::servsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::servs >::value();
  }
  static const char* value(const ::pkg::servsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::servsRequest> should match
// service_traits::DataType< ::pkg::servs >
template<>
struct DataType< ::pkg::servsRequest>
{
  static const char* value()
  {
    return DataType< ::pkg::servs >::value();
  }
  static const char* value(const ::pkg::servsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg::servsResponse> should match
// service_traits::MD5Sum< ::pkg::servs >
template<>
struct MD5Sum< ::pkg::servsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::servs >::value();
  }
  static const char* value(const ::pkg::servsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::servsResponse> should match
// service_traits::DataType< ::pkg::servs >
template<>
struct DataType< ::pkg::servsResponse>
{
  static const char* value()
  {
    return DataType< ::pkg::servs >::value();
  }
  static const char* value(const ::pkg::servsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_MESSAGE_SERVS_H
